osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "6"

os:
  - linux
  - osx

cache:
  directories:
    - web/node_modules
    - electron/node_modules

addons:
  apt:
    packages:
      - libsecret-1-0


install:
  - nvm install 6
  - npm install electron-builder@next
  - cd web
  - npm install
  - cd ../electron
  - npm install
  - cd ../
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - cd web
  - npm run electron
  - npm run postelectron
  - cd ../electron
  - npm run release
  - cd ../

deploy:
  provider: bitballoon
  site-id:
    secure: "censor-beaver-60124"
  access-token:
    secure: "4cd1bafba705679dd03e76f4e2a1a8e75eb4d8d56966fed41819c3a4793c3251"
  local-dir: "electron/releases/"